### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/etherpad_mypads_ynh#151]
### Describe the bug

When connecting to the homepage of my Etherpad instance, both typing the url from scratch and clicking on its tile on the Yunohost dashboard, I get error 502:

<img width="1440" alt="Screenshot 2021-10-07 at 10 50 03 PM" src="https://user-images.githubusercontent.com/42862428/136460314-38c2ceea-fe51-4a8b-b02f-d2de87e9e118.png">

<br>
<br>

### Context

- Hardware: *VPS*
- YunoHost version: 4.2.8.3
- I have access to my server: *Through SSH and web interface*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain: *screenshots have a dark background only because I use dark reader*
- Using, or trying to install package version/branch: *1.8.14~ynh2*

<img width="1133" alt="Screenshot 2021-10-07 at 10 52 04 PM" src="https://user-images.githubusercontent.com/42862428/136460977-65f20cb9-2b1e-4bf0-a101-1fd542b8b26e.png">

<br>
<br>

### Steps to reproduce

- clicking on the Etherpads tile or directly typing the URL
- getting the error

### Expected behavior

Seeing the Etherpad homepage

### Logs

No logs.

**Comment by jose1711** [comment]
I ran into the same problem when installing various plugins. By trial&error I isolated the issue to `fileupload` plugin (https://www.npmjs.com/package/ep_fileupload) which I also see in the log you provided. The fix was:
```
rm -r /var/www/etherpad_mypads/node_modules/ep_fileupload
systemctl restart etherpad_mypads.service
```
The plugin itself does not seem to be well maintained so that could be the reason. I don't believe this has anything to do with YNH package though.
