### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/etherpad_mypads_ynh#25]
Hi
I wanted to know:
1. What is the benefit of the MyPad admin interface?(It don't have anything special,as users are needed to be searched manually too)
2. Is the admin password asked while installation both for the main admin and MyPad plugin? If yes, then how to change the admin password for MyPad plugin?
3. I want to have a plugin which shows me all the pads with there last access date and the user who created it so that I can delete the pads manually after the pad has not been used for long time.
4. There is no logout option in the main admin interface. Is that done deliberately?
5. How can I no. of users registered and give them limited the space for there pads?

Any user case with the help of plugins for the productivity are most welcomed to share them(there are lot of plugins).

Thanks

**Comment by maniackcrudelis** [comment]
Hi anmol

1. I agree with you, this admin interface isn't really usefull.
2. Yes, it's the same password.
But, how to change it !? It's a good question, I'm not sure you can have different passwords.
There's nothing about that in the repository of mypads.
3. Did you had a look at https://static.etherpad.org/plugins.html ?
You can install a plugin from the admin panel of etherpad.
4. Huh, the only things I can say is, it's not up to me.
5. I hope it's something coming up with mypads. But I'm not sure they're about to add any new features for now.

**Comment by ldidry** [comment]
1. You'll be able to see all users from MyPads admin interface in 1.5.0 (https://framagit.org/framasoft/Etherpad/ep_mypads/issues/117)
2. You can't change, it uses Etherpad admin password.
3. Yes, use a plugin
4. Yep, it's Etherpad's stuff, so you should ask on https://github.com/ether/etherpad-lite/issues/
5. If nobody wrote an issue about it on https://framagit.org/framasoft/Etherpad/ep_mypads/issues, it will never be fixed. We're not against implementing new features (just have a look at all the new features since the version 1.1.0: https://framagit.org/framasoft/Etherpad/ep_mypads/tags) but I must warned you: I'll soon stop working on MyPads (it's kind of exhausting)

**Comment by anmol26s** [comment]
Hi @ldidry 
Thank you so much for taking out your precious time to answer my questions. 
1. I will be waiting for the 1.5.0
2. I got it now, how they work.
3. Plugin solves this issue. But plugins are not getting installed now. see this issue https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/39
4. I will open an issue on Etherpad lite repo page.
5. This one is not that important. But I will still open an issue for it, so that someday,someone gets motivated and add this feature.

Once again thanks for the work you are doing for the development of the this great app.
